spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/v1/hub/**
          filters:
            - "RewritePath=/v1/hub(?:/(?<path>.*))?, /\\${path}"

        - id: product-service

          uri: lb://product-service
          predicates:
            - Path=/v1/product/**
          filters:
            - "RewritePath=/v1/product(?:/(?<path>.*))?, /\\${path}"

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/user/**
          filters:
            - "RewritePath=/v1/user(?:/(?<path>.*))?, /\\${path}"

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v1/order/**
          filters:
            - "RewritePath=/v1/order(?:/(?<path>.*))?, /\\${path}"
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/fallback/order

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: full
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /user-service/v3/api-docs
        name: USER API
      - url: /hub-service/v3/api-docs
        name: HUB API
      - url: /order-service/v3/api-docs
        name: ORDER API

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 2                           # 슬라이딩 윈도우에 포함할 최근 호출 수 (통계 집계 기준)
        # 윈도우 크기가 크면 안정적인 통계, 작으면 민감도가 증가
        minimumNumberOfCalls: 1                         # 통계 집계를 시작하기 위한 최소 호출 수
        # 이 값보다 호출이 적으면 실패율 기반 판단을 하지 않음
        permittedNumberOfCallsInHalfOpenState: 2       # half-open 상태에서 허용할 시도 호출 수
        # 이 수치만큼 성공하면 closed로 전환 가능
        automaticTransitionFromOpenToHalfOpenEnabled: true
        # true면 open 상태에서 waitDuration 만료 후 자동으로 half-open 전환 시도
        waitDurationInOpenState: 2s                     # open 상태에서 다음 검사(half-open)로 전환까지 대기 시간
        # 단위: s (위 예시는 5초). 운영 환경에선 더 길게 설정 권장(예: 몇십 초)
        failureRateThreshold: 50                        # 실패 허용 비율(%) — 이 비율 이상이면 회로를 open으로 전환
        # 예: 50 -> 실패율이 50% 이상이면 오픈
        eventConsumerBufferSize: 10                     # CircuitBreaker 이벤트 버퍼 크기(모니터링/리스너용)
    instances:
      orderServiceCircuitBreaker:
        baseConfig: default                            # 위에 정의한 default 설정을 이 인스턴스에 적용